"""Create RespuestaDetalle table

Revision ID: 54d28ac7bbfd
Revises: 
Create Date: 2025-01-29 13:43:24.015178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d28ac7bbfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respuesta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respuesta_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['respuesta_id'], ['respuesta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.alter_column('agente_nombre',
               existing_type=sa.VARCHAR(length=150, collation='Modern_Spanish_CI_AS'),
               nullable=False)
        batch_op.create_foreign_key(None, 'usuario', ['agente_id'], ['id'])
        batch_op.drop_column('tercera')
        batch_op.drop_column('primera')
        batch_op.drop_column('segunda')
        batch_op.drop_column('cuarta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuarta', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('segunda', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('primera', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tercera', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('agente_nombre',
               existing_type=sa.VARCHAR(length=150, collation='Modern_Spanish_CI_AS'),
               nullable=True)

    op.drop_table('respuesta_detalle')
    # ### end Alembic commands ###
