"""Nivel en detalle de respuestas

Revision ID: 9ff2ac28ccf6
Revises: 54d28ac7bbfd
Create Date: 2025-01-30 11:36:38.374490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff2ac28ccf6'
down_revision = '54d28ac7bbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta_detalle', schema=None) as batch_op:
        batch_op.drop_column('nivel')

    # ### end Alembic commands ###
