"""Agregar columnas de respuestas (Receptor y Suma)

Revision ID: db07cb87e03d
Revises: 
Create Date: 2024-12-27 11:41:15.476942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db07cb87e03d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('suma_respuestas', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.drop_column('suma_respuestas')
        batch_op.drop_column('cliente')

    # ### end Alembic commands ###
